name: Deploy

on: push

jobs:
  test:
    name: Test app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build app
        run: npm ci

      - name: Test app
        run: npm test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install packages
        run: npm ci

      - name: Build app
        run: npm build

      - name: deploy
        run: echo "Deploying..."
